name: keep-supabase-alive (twice daily)

on:
  schedule:
    - cron: "0 6 * * *"    # 06:00 UTC
    - cron: "0 18 * * *"   # 18:00 UTC
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL_PROJECT_A }}
      SUPABASE_ANON: ${{ secrets.SUPABASE_ANON_PROJECT_A }}
    steps:
      - name: Ping RPC healthcheck
        run: |
          set -e
          curl -sS -X POST "$SUPABASE_URL/rest/v1/rpc/healthcheck" \
            -H "apikey: $SUPABASE_ANON" \
            -H "Authorization: Bearer $SUPABASE_ANON" \
            -H "Content-Type: application/json" \
            -d '{}' | jq .
